name: Package and release

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master
  paths-ignore:
    - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout addon
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1"

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install dependencies
        run: |
          luarocks install busted

      - name: Run tests
        run: busted .

  release:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Package and release
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
